import type { Tariff } from './types';

export const mockTariffs: Tariff[] = [
  {
    id: 'eco-saver-12',
    provider: 'GreenEnergy Inc.',
    tariffName: 'Eco Saver 12',
    price: 0.15,
    contractLength: 12,
    renewableEnergyPercentage: 100,
    otherBenefits: 'Free smart thermostat included.',
    providerLogoUrl: 'https://placehold.co/120x40.png',
  },
  {
    id: 'flex-power-24',
    provider: 'PowerGrid Co.',
    tariffName: 'Flex Power 24',
    price: 0.12,
    contractLength: 24,
    renewableEnergyPercentage: 20,
    otherBenefits: 'No exit fees. Variable rate.',
    providerLogoUrl: 'https://placehold.co/120x40.png',
  },
  {
    id: 'sunshine-fixed',
    provider: 'SolarWinds',
    tariffName: 'Sunshine Fixed',
    price: 0.18,
    contractLength: 18,
    renewableEnergyPercentage: 80,
    otherBenefits: 'Fixed price for 18 months. Support solar farms.',
    providerLogoUrl: 'https://placehold.co/120x40.png',
  },
  {
    id: 'city-basic',
    provider: 'Urban Electric',
    tariffName: 'City Basic',
    price: 0.11,
    contractLength: 12,
    renewableEnergyPercentage: 0,
    otherBenefits: 'Lowest price guarantee for city residents.',
    providerLogoUrl: 'https://placehold.co/120x40.png',
  },
  {
    id: 'night-owl',
    provider: 'PowerGrid Co.',
    tariffName: 'Night Owl',
    price: 0.09,
    contractLength: 12,
    renewableEnergyPercentage: 20,
    otherBenefits: 'Cheaper electricity from 11 PM to 7 AM.',
    providerLogoUrl: 'https://placehold.co/120x40.png',
  },
  {
    id: 'green-giant',
    provider: 'GreenEnergy Inc.',
    tariffName: 'Green Giant',
    price: 0.16,
    contractLength: 36,
    renewableEnergyPercentage: 100,
    otherBenefits: 'Long-term price stability and support for new green projects.',
    providerLogoUrl: 'https://placehold.co/120x40.png',
  },
];
